spring:
  docker:
    compose:
      enabled: false
  datasource:
  url: jdbc:postgresql://localhost:5432/registration
  username: 
  password:

server:
  error:
    include-message: always
    include-binding-errors: always

